x_offset: -0.01
y_offset: 0
z_offset: 0.02
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: 13
period_time: 600
dsp_ratio: 0.3
step_forward_back_ratio: 0.28
foot_height: 0.04
swing_right_left: 0.03
swing_top_down: 0.005
pelvis_offset: 3
arm_swing_gain: 1.5
balance_knee_gain: 1
balance_ankle_pitch_gain: 0.5
balance_hip_roll_gain: 0.9
balance_ankle_roll_gain: 0.3
p_gain: 0
i_gain: 0
d_gain: 0