cm_740 :   # MX-28
   return_delay_time    :  1    # item name : value
#   operating_mode        :  3
#   shutdown              :  58
#   homing_offset         :  0
#   torque_limit          :  310
#   min_position_limit       : 0
#   max_position_limit       : 4095
#   goal_torque          : 310
#   goal_velocity        : 0
#   goal_acceleration    : 0
#   position_P_gain      : 32
#   velocity_P_gain      : 180
#   velocity_I_gain      : 452
#   indirect_address_1    :       # indirect address
#     1  :                          # start index (1 ~ 256)
#       - present_position            # addr length : 4
#       - present_velocity            # addr length : 4
#       - present_current             # addr length : 2
#       - present_voltage             # addr length : 2
#       - present_temperature         # addr length : 1
